<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rover">

  <!-- Properties -->
  <xacro:property name="chassis_length" value="0.9"/>
  <xacro:property name="chassis_width" value="0.7"/>
  <xacro:property name="chassis_height" value="0.2"/>
  <xacro:property name="chassis_z_offset" value="0.15"/>

  <xacro:property name="wheel_radius" value="0.0762"/>
  <xacro:property name="wheel_width" value="0.1"/>
  <xacro:property name="track_width" value="0.686"/>

  <xacro:property name="wheelbase_front" value="0.3"/>
  <xacro:property name="wheelbase_rear" value="-0.3"/>

  <xacro:property name="camera_x" value="0.35"/>
  <xacro:property name="camera_z" value="0.45"/>

  <!-- ZED2i geometry constants from zed_wrapper macro -->
  <xacro:property name="zed_height" value="0.03"/>
  <xacro:property name="zed_baseline" value="0.12"/>
  <xacro:property name="zed_optical_offset_x" value="-0.01"/>

  <!-- Base footprint (ground plane projection) -->
  <link name="base_footprint"/>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${chassis_z_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="dark_gray">
        <color rgba="0.3 0.3 0.3 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_z_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Wheel macro -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} 0" rpy="${-pi/2} 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Left wheels (y = +track_width/2) -->
  <xacro:wheel name="left_wheel_front"  x="${wheelbase_front}" y="${track_width/2}"/>
  <xacro:wheel name="left_wheel_mid"    x="0"                  y="${track_width/2}"/>
  <xacro:wheel name="left_wheel_rear"   x="${wheelbase_rear}"   y="${track_width/2}"/>

  <!-- Right wheels (y = -track_width/2) -->
  <xacro:wheel name="right_wheel_front" x="${wheelbase_front}"  y="${-track_width/2}"/>
  <xacro:wheel name="right_wheel_mid"   x="0"                   y="${-track_width/2}"/>
  <xacro:wheel name="right_wheel_rear"  x="${wheelbase_rear}"    y="${-track_width/2}"/>

  <!-- ZED 2i camera mount point -->
  <link name="zed_camera_link">
    <visual>
      <geometry>
        <box size="0.175 0.03 0.033"/>
      </geometry>
      <material name="silver">
        <color rgba="0.7 0.7 0.7 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="zed_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="zed_camera_link"/>
    <origin xyz="${camera_x} 0 ${camera_z}" rpy="0 0 0"/>
  </joint>

  <!-- ZED frame chain required by zed_wrapper positional tracking -->
  <link name="zed_camera_center"/>
  <joint name="zed_camera_center_joint" type="fixed">
    <parent link="zed_camera_link"/>
    <child link="zed_camera_center"/>
    <origin xyz="0 0 ${zed_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="zed_left_camera_frame"/>
  <joint name="zed_left_camera_joint" type="fixed">
    <parent link="zed_camera_center"/>
    <child link="zed_left_camera_frame"/>
    <origin xyz="${zed_optical_offset_x} ${zed_baseline/2} 0" rpy="0 0 0"/>
  </joint>

  <link name="zed_left_camera_optical_frame"/>
  <joint name="zed_left_camera_optical_joint" type="fixed">
    <parent link="zed_left_camera_frame"/>
    <child link="zed_left_camera_optical_frame"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <link name="zed_right_camera_frame"/>
  <joint name="zed_right_camera_joint" type="fixed">
    <parent link="zed_camera_center"/>
    <child link="zed_right_camera_frame"/>
    <origin xyz="${zed_optical_offset_x} ${-zed_baseline/2} 0" rpy="0 0 0"/>
  </joint>

  <link name="zed_right_camera_optical_frame"/>
  <joint name="zed_right_camera_optical_joint" type="fixed">
    <parent link="zed_right_camera_frame"/>
    <child link="zed_right_camera_optical_frame"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- Compatibility aliases for zed_wrapper frame naming variants -->
  <link name="zed_base_link"/>
  <joint name="zed_base_link_joint" type="fixed">
    <parent link="zed_camera_link"/>
    <child link="zed_base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="zed_left_camera"/>
  <joint name="zed_left_camera_alias_joint" type="fixed">
    <parent link="zed_left_camera_frame"/>
    <child link="zed_left_camera"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="zed_left_camera_optical"/>
  <joint name="zed_left_camera_optical_alias_joint" type="fixed">
    <parent link="zed_left_camera_optical_frame"/>
    <child link="zed_left_camera_optical"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="zed_right_camera"/>
  <joint name="zed_right_camera_alias_joint" type="fixed">
    <parent link="zed_right_camera_frame"/>
    <child link="zed_right_camera"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="zed_right_camera_optical"/>
  <joint name="zed_right_camera_optical_alias_joint" type="fixed">
    <parent link="zed_right_camera_optical_frame"/>
    <child link="zed_right_camera_optical"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Extra compatibility aliases for camera-model-prefixed frame variants -->
  <link name="zed2i_camera_link"/>
  <joint name="zed2i_camera_link_alias_joint" type="fixed">
    <parent link="zed_camera_link"/>
    <child link="zed2i_camera_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="zed2i_base_link"/>
  <joint name="zed2i_base_link_alias_joint" type="fixed">
    <parent link="zed_base_link"/>
    <child link="zed2i_base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="zed2i_camera_center"/>
  <joint name="zed2i_camera_center_alias_joint" type="fixed">
    <parent link="zed_camera_center"/>
    <child link="zed2i_camera_center"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="zed2i_left_camera_frame"/>
  <joint name="zed2i_left_camera_frame_alias_joint" type="fixed">
    <parent link="zed_left_camera_frame"/>
    <child link="zed2i_left_camera_frame"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="zed2i_left_camera_optical_frame"/>
  <joint name="zed2i_left_camera_optical_frame_alias_joint" type="fixed">
    <parent link="zed_left_camera_optical_frame"/>
    <child link="zed2i_left_camera_optical_frame"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="zed2i_right_camera_frame"/>
  <joint name="zed2i_right_camera_frame_alias_joint" type="fixed">
    <parent link="zed_right_camera_frame"/>
    <child link="zed2i_right_camera_frame"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="zed2i_right_camera_optical_frame"/>
  <joint name="zed2i_right_camera_optical_frame_alias_joint" type="fixed">
    <parent link="zed_right_camera_optical_frame"/>
    <child link="zed2i_right_camera_optical_frame"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>
